# Generated by Django 2.1.5 on 2019-01-15 08:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=32, unique=True)),
                ('sensor_type', models.CharField(max_length=32)),
                ('sensor_phys_addr', models.CharField(max_length=128)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SensorValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_value', models.CharField(max_length=8)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sensor_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Sensor')),
            ],
        ),
    ]
