# Generated by Django 2.1.3 on 2018-11-23 08:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=32, unique=True)),
                ('worker_type', models.CharField(max_length=32)),
                ('worker_manual', models.BooleanField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_state', models.CharField(max_length=8)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('worker_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Worker')),
            ],
        ),
    ]
